/**
* Generated by PluginGenerator from webgme on Wed Mar 11 2015 17:57:33 GMT-0500 (Central Daylight Time).
*/

define([], function () {
    'use strict';
    return {
        'FCO': '/1',
    };
});